debugging: re-add random password
trying to get past this error:

  Error: Could not satisfy plugin requirements

  Plugin reinitialization required. Please run "terraform init".

  Plugins are external binaries that Terraform uses to access and manipulate
  resources. The configuration provided requires plugins which can't be located,
  don't satisfy the version constraints, or are otherwise incompatible.

  Terraform automatically discovers provider requirements from your
  configuration, including providers used in child modules. To see the
  requirements and constraints from each module, run "terraform providers".

  Error: provider.random: no suitable version installed
    version requirements: "(any version)"
    versions installed: none

Signed-off-by: Alex Suraci <asuraci@pivotal.io>
Co-authored-by: Aidan Oldershaw <aoldershaw@pivotal.io>